spring:
  application:
    name: rentspace

  datasource:
    url: jdbc:mysql://localhost:3306/rental_system_db
    username: root
    password: SK@0555
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true